apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "mutate-policy"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
  failurePolicy: Fail
  reinvocationPolicy: Never
  matchConditions:
    - name: check-annotation
      expression: >
        !object.metadata.?annotations[?'cluster-autoscaler.kubernetes.io/safe-to-evict'].hasValue()
  mutations:
    - patchType: "ApplyConfiguration"
      applyConfiguration:
        expression: >
            has(object.spec.volumes) && object.spec.volumes.exists(v, has(v.emptyDir)) ?
                Object{
                  metadata: Object.metadata{
                    annotations: {
                      "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
                    }
                  }
                } :
                Object{}
---
# Policy Binding
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: "mutate-policy-binding"
spec:
  policyName: "mutate-policy"
