apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: "mutate-policy"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
  failurePolicy: Fail
  reinvocationPolicy: Never
  mutations:
    - patchType: "ApplyConfiguration"
      applyConfiguration:
        expression: >
          Object{
              spec: Object.spec{
                  containers: object.spec.containers.map(c,
                      Object.spec.containers{
                          name: c.name,
                          securityContext: Object.spec.containers.securityContext{
                              runAsNonRoot: true
                          }
                      }
                  )
              }
          }
---
# Policy Binding
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: "mutate-policy-binding"
spec:
  policyName: "mutate-policy"
